# Generated by Django 4.2.4 on 2023-10-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='consultor_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('run', models.IntegerField()),
                ('ape_pat', models.CharField(max_length=30)),
                ('ape_mat', models.CharField(max_length=30)),
                ('fecha_def', models.DateField()),
                ('id_hospital', models.ForeignKey(db_column='id_hospital', on_delete=django.db.models.deletion.CASCADE, to='consultor_app.hospital')),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='consultor_app.region')),
            ],
        ),
    ]
