# Generated by Django 4.2.4 on 2023-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultor_app', '0002_hospital_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id_estudio', models.AutoField(db_column='id_estudio', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('cuerpo', models.CharField(max_length=5000)),
                ('conclusion', models.CharField(max_length=1000)),
            ],
        ),
    ]
